# listen on http
defaultEntryPoints = ["http"]
 
# entry point of http/80
[entryPoints]
  [entryPoints.http]
  address = ":80"

# this allows traefik to interact with docker
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedByDefault = false

 