version: '3'
services:
  vault:
    image: vault
    ports:
      - "8200:8200"
    networks:
      - network-secrets
    volumes:
      - vault-fs:/mnt/vault/file
      - ${PWD}/config.json:/home/vault/config.json
    cap_add:
      - IPC_LOCK
    command: /bin/sh -c "chown vault:vault /mnt/vault/file && /bin/vault server -config /home/vault/config.json"
  python:
    build: ./containers/orange-python
    ports:
      - "80:80"
    networks:
      - network-secrets
    environment:
      - VAULT_URL=http://vault:8200
      - VAULT_TOKEN=s.dsOC6zOAiuCAhVkJnFoTQgYF
volumes:
  vault-fs:
networks:
  network-secrets:
