version: '3.3'
services:
  traefik:
    image: traefik:v2.0-alpine
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Access to Docker
      - ./containers/traefik/traefik.yml:/traefik.yml # Traefik configuration
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik-network
  blue-python:
    image: mrmcshane/python:06-blue
    ports:
      - "30003:80"
    labels:
      - traefik.http.routers.blue-python.rule=Host(`blue-python.localhost`)
    networks:
      - traefik-network
  green-python:
    image: mrmcshane/python:06-green
    ports:
      - "30004:80"
    labels:
      - traefik.http.routers.green-python.rule=Host(`green-python.localhost`)
    networks:
      - traefik-network
  python-backend:
    image: "mariadb/server"
    environment:
      MARIADB_ROOT_PASSWORD: pass
    ports:
      - "30005:3306"
    volumes:
      - python-backend-data:/var/lib/mysql
    labels:      
      - traefik.enabled=false
    networks:
      - traefik-network
volumes:
  python-backend-data:
networks:
  traefik-network: